# -*- encoding: utf-8 -*-

=begin
#pir5

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.3-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "pir5/version"

Gem::Specification.new do |s|
  s.name        = "pir5"
  s.version     = Pir5::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["pir5"]
  s.email       = [""]
  s.homepage    = "https://github.com/pir5/pir5-rb"
  s.summary     = "pir5 Ruby Gem"
  s.description = "pir5 client"
  s.license     = 'MIT'
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
