=begin
#pir5

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.3-SNAPSHOT

=end

# Common files
require 'pir5/api_client'
require 'pir5/api_error'
require 'pir5/version'
require 'pir5/configuration'

# Models
require 'pir5/models/model_domain'
require 'pir5/models/model_record'

# APIs
require 'pir5/api/default_api'

module Pir5
  class << self
    # Customize default settings for the SDK using block.
    #   Pir5.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
